version: '3'
services:
  db:
    image: postgres
    container_name: hairshop-db
    restart: always
    volumes:
      - hairshop:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'password'
      TZ: 'Asia/Seoul'

volumes:
  hairshop:
